openapi: 3.0.0
info:
  title: Aurora API
  description: Public API for interating with lights managed by the Aurora Home Hub.
  version: 0.1.9
servers:
  - url: https://aurora.ngrok.io/api/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /lights:
    get:
      summary: Returns a list of lights.
      description: Retuns a list of lights on the network.
      responses:
        '200':    # status code
          description: A JSON array of lights
          content:
            application/json:
              schema: 
                # TODO - use refs for actual schemas
                type: array
                items: 
                  type: string
  /animations:
    get:
      summary: Returns a list of available animations.
      description: Returns a list of available animations. These animations can be uses to set a given light's animation using the /lights/<lightId>/animation route.
      responses:
        '200':    # status code
          description: A JSON array of animations
          content:
            application/json:
              schema: 
                # TODO - use refs for actual schemas
                type: array
                items: 
                  type: string
