version: '3.9'
services:
  aurora_server:
    image: zackmattor/aurora-server
    networks:
      - auroranet
    ports:
      - '8080:8080'
      - '1337:1337'
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password

volumes:
  influxdb-storage:
    driver: local
  grafana-storage:
    driver: local
  grafana-provisioning:
    driver: local

networks:
  auroranet:
    driver: bridge
